//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.cloudsdale.android.network;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import org.cloudsdale.android.Cloudsdale;

public final class CloudsdaleApiClient_
    extends CloudsdaleApiClient
{

    private Context context_;

    private CloudsdaleApiClient_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
            cloudsdale = ((Cloudsdale) activity.getApplication());
        }
    }

    public static CloudsdaleApiClient_ getInstance_(Context context) {
        return new CloudsdaleApiClient_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
