//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.cloudsdale.android;

import android.content.res.Resources;
import org.cloudsdale.android.R.string;
import org.cloudsdale.android.network.CloudsdaleApiClient_;

public final class Cloudsdale_
    extends Cloudsdale
{


    private void init_() {
        Resources resources_ = this.getResources();
        configUrl = resources_.getString(string.config_url);
        cloudsdaleApi = CloudsdaleApiClient_.getInstance_(this);
        dataStore = DataStore_.getInstance_(this);
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
