//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.cloudsdale.android;

import android.app.Activity;
import android.content.Context;
import android.content.res.Resources;
import android.view.View;
import org.cloudsdale.android.R.string;

public final class DataStore_
    extends DataStore
{

    private Context context_;

    private DataStore_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
            cloudsdale = ((Cloudsdale) activity.getApplication());
        }
        Resources resources_ = context_.getResources();
        accountType = resources_.getString(string.account_type);
    }

    public static DataStore_ getInstance_(Context context) {
        return new DataStore_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
